### ISSUE TITLE
In Machine Learning Explainability Solution Is Wrong?

### ISSUE THREAD

**Issue by harsha7addanki** [Kaggle/learntools#357]
When I Did My Work Check Is Saying Incorrect Even When Pasting Solution

**Comment by thecodinganalyst** [comment]
> When I Did My Work Check Is Saying Incorrect Even When Pasting Solution

Same here. The results of Ex 2 and Ex 4 in Permutation Importance are a bit way off. I can still get away for Ex 2 when i specify random_state=0, but not for Ex 4. The 1st 4 values in the array is way too low at 0.0X when the same results in Ex 2 is 0.X. Seems like the performance variance is used instead of the accuracy.
Also, the tolerance is set at 0.1 but it was 0.3 in Ex 2

**Comment by ryanholbrook** [comment]
(PR #361) This should go live on Kaggle soon, but in the meantime you could paste `!pip install -U -t /kaggle/working/ git+https://github.com/Kaggle/learntools.git` into a code cell at the very start of your notebook. This will install a copy of the checking code with the fix included.

Thanks for the heads up and let us know if you have any more trouble!
